  CREATE TABLE IF NOT EXISTS BGD_BASE (
	BH VARCHAR(10) NOT NULL ,
	YLRBH VARCHAR(15) NULL ,
	HGBH VARCHAR(30) NULL ,
	JCKKA CHAR(4) NULL ,
	BAH VARCHAR(20) NULL,
	HTXYH VARCHAR (100) NULL,
	JCKRQ DATETIME NULL,
	SBRQ DATETIME NULL,
	JYDW VARCHAR(15) NULL,
	YSFS CHAR(2) NULL,
	YSGJMC VARCHAR(30) NULL,
	SHDW VARCHAR (40) NULL,
	FHDW VARCHAR(15) NULL,
	SBDW VARCHAR(15) NULL,
	HCH VARCHAR(15) NULL,
	TYDH VARCHAR(10) NULL,
	MYFS CHAR(4) NULL,
	ZMXZ CHAR(3) NULL,
	JHFS CHAR(2) NULL,
	ZSBL DECIMAL (18,4) NULL,
	NSDW VARCHAR(15) NULL,
	XKZH VARCHAR(15) NULL,
	GJ CHAR(3) NULL,
	ZYG CHAR(4) NULL,
	JND VARCHAR(20) NULL,
	PZWH VARCHAR(15) NULL,
	CJFS CHAR(2) NULL,
	YFFS CHAR(4) NULL,
	YFBZ VARCHAR (12) NULL,
	YF DECIMAL (16,4) NULL,
	BFFS CHAR(4) NULL,
	BFBZ VARCHAR (12) NULL,
	BF DECIMAL (16,4) NULL,
	ZFFS CHAR(4) NULL,
	ZFBZ VARCHAR (12) NULL,
	ZF DECIMAL (16,4) NULL,
	JS INT NULL,
	BZZL CHAR (2) NULL,
	MZ DECIMAL (16,2) NULL,
	JZ DECIMAL (16,2) NULL,
	JZXH VARCHAR (20) NULL,
	SFDZ VARCHAR (50) NULL,
	SCCJ VARCHAR (30) NULL,
	YT VARCHAR (20) NULL,
	BZ VARCHAR (200) NULL,
	BGDLX CHAR (8) NULL,
	LB CHAR (2) NULL,
	HTSJ DATETIME NULL,
	DW VARCHAR (50) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	

  CREATE TABLE IF NOT EXISTS BGD_LIST (
	BH VARCHAR(12) NOT NULL ,
	BGDBH VARCHAR(10) NULL ,
	XH CHAR(2) NULL ,
	SPBH VARCHAR(15) NULL ,
	SPMC VARCHAR(50) NULL ,
	SPGG VARCHAR(150) NULL ,
	SL DECIMAL(16,4) NULL,
	ZL DECIMAL(16,2) NULL,
	DW VARCHAR(20) NULL ,
	JS INT NULL ,
	MDG CHAR(3) NULL ,
	DJ DECIMAL(16,4) NULL,
	ZJ DECIMAL(16,4) NULL,
	BZ CHAR(2) NULL,
	ZM CHAR(2) NULL,
	MZ DECIMAL(18,0) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_BZ (
	BH CHAR(2) NOT NULL ,
	BZ VARCHAR(10) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	

  CREATE TABLE IF NOT EXISTS ZD_BZZL (
	BH CHAR(2) NOT NULL ,
	BZZL VARCHAR(10) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_CJFS (
	BH CHAR(2) NOT NULL ,
	CJFS VARCHAR(10) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_CKKA (
	BH CHAR(4) NOT NULL ,
	CKKA VARCHAR(20) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;




  CREATE TABLE IF NOT EXISTS BGD_JZX (
	BH VARCHAR(15) NOT NULL ,
	BGDBH VARCHAR(10) NOT NULL ,
	JZXGG CHAR(2) NULL,
	JZXZL VARCHAR(15) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_JZXGG (
	BH CHAR(4) NOT NULL ,
	JZXGG CHAR(2) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

  CREATE TABLE IF NOT EXISTS BGD_SF (
	BH VARCHAR(15) NOT NULL ,
	BGDBH VARCHAR(10) NOT NULL ,
	SFDM CHAR(2) NULL,
	SFDZBH VARCHAR(15) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

  CREATE TABLE IF NOT EXISTS ZD_SFDM (
	BH CHAR(4) NOT NULL ,
	SFDM CHAR(2) NULL,
	SFMC VARCHAR(15) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;





  CREATE TABLE IF NOT EXISTS ZD_DW (
	BH VARCHAR(15) NOT NULL ,
	DW VARCHAR(50) NULL,
	LXR VARCHAR(10) NULL,
	LXDH VARCHAR(50) NULL,
	DZ VARCHAR(50) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_JHFS (
	BH CHAR(2) NOT NULL ,
	JHFS VARCHAR(10) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_JNHYD (
	BH CHAR(5) NOT NULL ,
	JNHYD VARCHAR(10) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_MYFS (
	BH CHAR(4) NOT NULL ,
	MYFS VARCHAR(10) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_sp (
	BH VARCHAR(15) NOT NULL ,
	SPBH VARCHAR(50) NULL,
	SPMC VARCHAR(50) NULL,
	SPGG VARCHAR(50) NULL,
	DW VARCHAR(20) NULL,
	LRSJ DATETIME NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_USER (
	UID VARCHAR(16) NOT NULL ,
	PWD VARCHAR(16) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_YDG (
	BH CHAR(3) NOT NULL ,
	YDG VARCHAR(20) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_YSFS (
	BH CHAR(2) NOT NULL ,
	YSFS VARCHAR(20) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_YSFS (
	BH CHAR(2) NOT NULL ,
	YSFS VARCHAR(20) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_ZMXZ (
	BH CHAR(3) NOT NULL ,
	ZMXZ VARCHAR(20) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_ZYG (
	BH CHAR(4) NOT NULL ,
	ZYG VARCHAR(20) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	
  CREATE TABLE IF NOT EXISTS ZD_JZX {
	BH CHAR(8) NOT NULL,
	 JZX CHAR(12) NULL
  } ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

/*
  CREATE TABLE IF NOT EXISTS ZD_NSDW (
	BH VARCHAR(8) NOT NULL ,
	NSDW VARCHAR(12) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO ZD_NSDW (BH, NSDW) VALUES ("1", "经营单位");
INSERT INTO ZD_NSDW (BH, NSDW) VALUES ("2", "收货单位");
INSERT INTO ZD_NSDW (BH, NSDW) VALUES ("3", "申报单位");


  CREATE TABLE IF NOT EXISTS ZD_FFS (
	BH VARCHAR(4) NOT NULL ,
	FFS VARCHAR(12) NULL
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO ZD_FFS (BH, FFS) VALUES (1, "率");
INSERT INTO ZD_FFS (BH, FFS) VALUES (2, "单价");
INSERT INTO ZD_FFS (BH, FFS) VALUES (3, "总价");
*/